apiVersion: v1
entries:
  webapp-db-java:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-04-17T14:54:16.4023231+02:00"
    description: Java frontend with a MySQL backend
    digest: 76fa4d44a8862c5e6caaa99ab5c84c95451630b4427b6cacb1009b636e4dee7f
    name: webapp-db-java
    urls:
    - webapp-db-java-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-17T14:54:16.398794+02:00"
