replicaCount: 1

service:
  type: LoadBalancer
  targetPort: 3000
  port: 80

ingress:
  enabled: true
  host: eoloserver-svc-arturisimo.cloud.okteto.net

mysql:
  enabled: false
  container:
    image: "mysql"
    tag: "8.0.28"

mongodb:
  enabled: false
  container:
    image: "mongo"
    tag: "5.0.6-focal"

rabbitmq:
  enabled: false
  container:
    image: "rabbitmq"
    tag: "3.9-management"


mysql_database: anuncios

mysql_host: mysql-service
mysql_db: eoloplantsdb
mysql_user: root
mysql_password: password
rabbitmq_url: amqp://root:password@rabbitmq-service

topo_host: toposervice-service
topo_port: "8181"
grpc_client_weatherserver_address: static://weatherservice-service:9090
spring_cloud_stream_rabbit_binder_nodes: rabbitmq-service:5672
spring_rabbitmq_host: rabbitmq-service
spring_rabbitmq_port: "5672"
spring_rabbitmq_username: root
spring_rabbitmq_password: password

mongodb_host: mongodb-service
mongodb_port: "27017"
mongodb_database: topoDB
mongodb_auth_database: admin
mongodb_username: root
mongodb_password: password

