# Default values for webapp-db-java.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: arturisimo/webapp-db-java
  tag: v2
  pullPolicy: Always

service:
  type: LoadBalancer
  targetPort: 8080
  port: 80

metrics:
  enabled: false

resources: 
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql_root_username: root
mysql_root_password: pass
mysql_database: jdbc:mysql://db/anuncios
mysql_host: db