---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toposervice
  replicas: 1
  template:
    metadata:
      labels:
        app: toposervice
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: toposervice
        image: codeurjc/toposervice:v1.0
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: {{ .Values.mongodb_host }}
        - name: SPRING_DATA_MONGODB_PORT
          value: {{ .Values.mongodb_port }}
        - name: SPRING_DATA_MONGODB_DATABASE
          value: {{ .Values.mongodb_database }}
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: {{ .Values.mongodb_auth_database }}
        - name: SPRING_DATA_MONGODB_USERNAME
          value: {{ .Values.mongodb_username }}
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: {{ .Values.mongodb_password }}
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: toposervice-service
  labels:
    app: toposervice
spec:
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: topo-port
  selector:
    app: toposervice
  type: ClusterIP